--legacy-peer-deps

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -18,8 +18,9 @@ jobs:
       uses: actions/setup-node@v3
       with:
         node-version: '20.x'
-    - name: Run npm install 
-      run: npm i
+    - run: node -v
+    - run: npm install --legacy-peer-deps
+    - run: npm audit fix || true  # Attempt to fix vulnerabilities, continue even if it fails      - run: npm run build  # Assuming you have a build script
     - name: Run eslint
       run: npm run lint
     - name: Run tests
